# Generated by Django 2.2.2 on 2019-06-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnorthodoxMom_blog', '0002_auto_20190609_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_comments',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='UnorthodoxMom_blog.Comments'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='product_list',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='UnorthodoxMom_blog.Products'),
        ),
    ]
