# Generated by Django 2.2.2 on 2019-06-09 06:48

import UnorthodoxMom_blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UnorthodoxMom_blog', '0003_auto_20190609_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='blog_comments',
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='product_list',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commenter',
        ),
        migrations.AddField(
            model_name='comments',
            name='blog_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='UnorthodoxMom_blog.Blog_Post'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='images',
            field=models.ImageField(upload_to=UnorthodoxMom_blog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='tags',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='video_link',
            field=models.TextField(max_length=1000),
        ),
    ]
