# Generated by Django 2.2.2 on 2019-06-09 06:50

import UnorthodoxMom_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnorthodoxMom_blog', '0004_auto_20190609_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='images',
            field=models.ImageField(blank=True, upload_to=UnorthodoxMom_blog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='video_link',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
